"""
title: Canonical bibliographic schema definitions.
"""

CANONICAL_FIELDS: tuple[str, ...] = (
    "id",
    "source",
    "source_id",
    "title",
    "abstract",
    "authors_raw",
    "authors",
    "journal",
    "source_title",
    "year",
    "publication_year",
    "publication_date",
    "journal_abbrev",
    "doi",
    "url",
    "author_keywords",
    "keywords_author",
    "keywords_index",
    "keywords_all",
    "references_raw",
    "references",
    "document_type",
    "language",
    "volume",
    "issue",
    "start_page",
    "end_page",
    "pages",
    "article_number",
    "page_count",
    "issn",
    "eissn",
    "isbn",
    "publisher",
    "affiliations",
    "institutions",
    "countries",
    "author_ids",
    "authors_with_affiliations",
    "publication_stage",
    "source_database",
    "open_access_status",
    "open_access_url",
    "license",
    "funders",
    "grants",
    "concepts",
    "wos_categories",
    "research_areas",
    "emails",
    "corresponding_author_address",
    "cited_by_count",
    "reference_count",
    "raw",
    "provider",
    "source_format",
)

BIBLIOMETRIX_FIELD_MAP: dict[str, str] = {
    "authors": "AU",
    "title": "TI",
    "source_title": "SO",
    "publication_year": "PY",
    "doi": "DI",
    "keywords_author": "DE",
    "keywords_index": "ID",
    "abstract": "AB",
    "document_type": "DT",
    "language": "LA",
    "references": "CR",
    "url": "URL",
    "cited_by_count": "TC",
}

FORMAT_EXTENSIONS: dict[str, str] = {
    ".ris": "ris",
    ".bib": "bibtex",
    ".bibtex": "bibtex",
    ".csv": "csv",
    ".tsv": "tsv",
    ".json": "json",
    ".jsonl": "jsonl",
    ".nbib": "nbib",
    ".txt": "plain_text",
    ".text": "plain_text",
    ".xml": "xml",
    ".yaml": "yaml",
    ".yml": "yaml",
}
