import { FormEvent, useMemo, useState } from "react";

import { DataTable } from "../../components/common/DataTable";
import { EmptyState } from "../../components/common/EmptyState";
import { useMatrix } from "../../api/queries";
import type { MatrixRequest } from "../../api/types";
import { dynamicColumns } from "./utils";
import { useActiveWorkspace } from "./workspace";

const matrixKinds = [
  "co_occurrence",
  "incidence",
  "collaboration",
  "co_citation",
  "bibliographic_coupling",
  "direct_citation",
];

const matrixUnits = [
  "keywords_all",
  "authors",
  "source_title",
  "references",
  "countries",
  "affiliations",
];

export function MatrixPage() {
  const { projectId, activeDatasetId } = useActiveWorkspace();
  const matrix = useMatrix(projectId, activeDatasetId);
  const [kind, setKind] = useState("co_occurrence");
  const [unit, setUnit] = useState("keywords_all");
  const [normalize, setNormalize] = useState("");
  const [minOccurrences, setMinOccurrences] = useState(1);

  const request = useMemo<MatrixRequest>(
    () => ({
      kind,
      unit,
      normalize: normalize || null,
      min_occurrences: minOccurrences,
      filters: {},
    }),
    [kind, minOccurrences, normalize, unit],
  );

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    matrix.mutate(request);
  }

  const tableRows = matrix.data?.data.table ?? [];

  return (
    <div className="page-stack">
      <section className="card section-heading">
        <span className="eyebrow">Matrices</span>
        <h2>Build bibliometric matrices</h2>
        <p>
          Matrices are generated by biblioflow and returned as plain tables for
          inspection, export, and downstream network generation.
        </p>
      </section>

      <section className="dashboard-grid">
        <form className="card form-card" onSubmit={onSubmit}>
          <div className="section-heading compact">
            <span className="eyebrow">Request</span>
            <h2>Matrix settings</h2>
          </div>
          <label>
            Matrix kind
            <select
              value={kind}
              onChange={(event) => setKind(event.target.value)}
            >
              {matrixKinds.map((option) => (
                <option key={option} value={option}>
                  {option.replaceAll("_", " ")}
                </option>
              ))}
            </select>
          </label>
          <label>
            Unit
            <select
              value={unit}
              onChange={(event) => setUnit(event.target.value)}
            >
              {matrixUnits.map((option) => (
                <option key={option} value={option}>
                  {option.replaceAll("_", " ")}
                </option>
              ))}
            </select>
          </label>
          <label>
            Normalization
            <select
              value={normalize}
              onChange={(event) => setNormalize(event.target.value)}
            >
              <option value="">None</option>
              <option value="association">Association strength</option>
            </select>
          </label>
          <label>
            Minimum occurrences
            <input
              type="number"
              min="1"
              value={minOccurrences}
              onChange={(event) =>
                setMinOccurrences(Math.max(Number(event.target.value), 1))
              }
            />
          </label>
          <button
            type="submit"
            className="button-primary"
            disabled={matrix.isPending}
          >
            {matrix.isPending ? "Building…" : "Build matrix"}
          </button>
          {matrix.isError && <p role="alert">{matrix.error.message}</p>}
        </form>

        <article className="card">
          <span className="eyebrow">Guidance</span>
          <h2>Choosing settings</h2>
          <ul className="guidance-list">
            <li>Use keyword co-occurrence for conceptual maps.</li>
            <li>Use author collaboration for social structure.</li>
            <li>
              Use co-citation or bibliographic coupling for intellectual
              structure.
            </li>
            <li>Raise minimum occurrences to reduce sparse matrices.</li>
          </ul>
        </article>
      </section>

      <section className="card">
        <div className="section-heading compact">
          <span className="eyebrow">Result</span>
          <h2>
            {matrix.data
              ? `${matrix.data.data.kind} / ${matrix.data.data.unit}`
              : "No matrix built yet"}
          </h2>
        </div>
        {matrix.data ? (
          <>
            <div className="workspace-meta result-meta">
              <span>{tableRows.length} rows</span>
              <span>Showing first 25 rows and up to 8 columns</span>
            </div>
            <DataTable
              rows={tableRows.slice(0, 25)}
              columns={dynamicColumns(tableRows, 8)}
              emptyMessage="The matrix result is empty."
            />
          </>
        ) : (
          <EmptyState title="Build a matrix to inspect the table" icon="▦">
            <p>Submit the settings above to run the matrix endpoint.</p>
          </EmptyState>
        )}
      </section>
    </div>
  );
}
